remote_theme: daattali/beautiful-jekyll

title: Impressum

author: Silas Meyer

navbar-links: 
  Website: "https://silas229.me"

avatar: "avatar.png"

social-network-links:
  email: "contact@silas229.me"
  github: silas229
  twitter: silas_229
  mastodon: chaos.social/@silas_229

defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "index.html"

exclude:
